CREATE TABLE IF NOT EXISTS ADVISORS
(
    ID BIGSERIAl PRIMARY KEY,
    EMAIL VARCHAR NOT NULL,
    USER_NAME VARCHAR NOT NULL UNIQUE,
    FIRST_NAME VARCHAR NOT NULL,
    LAST_NAME VARCHAR NOT NULL,
    ADVISOR_ROLE VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS APPLICANTS
(
    ID BIGSERIAl PRIMARY KEY,
    EMAIL VARCHAR NOT NULL,
    USER_NAME VARCHAR NOT NULL UNIQUE,
    FIRST_NAME VARCHAR NOT NULL,
    LAST_NAME VARCHAR NOT NULL,
    SSN VARCHAR NOT NULL UNIQUE,
    CITY VARCHAR NOT NULL,
    STREET VARCHAR NOT NULL,
    STREET_NUMBER NUMERIC NOT NULL,
    ZIP NUMERIC NOT NULL,
    APT NUMERIC
);

CREATE TABLE IF NOT EXISTS APPLICANT_PHONES
(
    PHONE_NUMBER VARCHAR NOT NULL,
    PHONE_TYPE VARCHAR NOT NULL,
    APPLICANT_ID BIGSERIAl NOT NULL,
    CONSTRAINT APPLICANT_PHONES_APPLICANT_ID_FK FOREIGN KEY(APPLICANT_ID) REFERENCES APPLICANTS(ID)
    );

CREATE INDEX APPLICANT_PHONES_APPLICANT_IDX ON APPLICANT_PHONES (APPLICANT_ID);

CREATE TABLE IF NOT EXISTS APPLICATIONS
(
    ID BIGSERIAl PRIMARY KEY,
    AMOUNT DECIMAL(12, 2) NOT NULL,
    STATUS VARCHAR NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT now(),
    ASSIGNED_DATE TIMESTAMP,
    RESOLVED_DATE TIMESTAMP,
    APPLICANT_ID BIGSERIAl NOT NULL,
    ADVISOR_ID INT,
    VERSION INT NOT NULL default 1,
    CONSTRAINT APPLICATIONS_APPLICANT_ID_FK FOREIGN KEY(APPLICANT_ID) REFERENCES APPLICANTS(ID),
    CONSTRAINT APPLICATIONS_ADVISOR_ID_FK FOREIGN KEY(ADVISOR_ID) REFERENCES ADVISORS(ID)
    );

CREATE INDEX APPLICATIONS_APPLICANT_IDX ON APPLICATIONS (APPLICANT_ID);
CREATE INDEX APPLICATIONS_ADVISOR_ID_IDX ON APPLICATIONS (ADVISOR_ID);


